version: '3'
services:
  kong:
    container_name: kong-dev
    build: .
    restart: always
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-postgres
      - KONG_PG_USERT=kong
      - KONG_PG_DATABASE=kong
      - KONG_LOG_LEVEL=debug
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_PLUGINS=bundled,demo-plugin
      - KONG_LUA_PACKAGE_PATH=/custom_plugin/?.lua;;
    volumes:
      - ./custom_plugin:/custom_plugin
      - ./kong:/kong
      - ./custom_plugin/kong/spec/04-custom-plugins:/kong/spec/04-custom-plugins
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    depends_on:
      - kong-postgres

  kong-test:
    container_name: kong-test
    build: .
    restart: always
    environment:
      - KONG_TEST_DATABASE=postgres
      - KONG_TEST_PG_HOST=kong-postgres
      - KONG_TEST_DNS_RESOLVER=127.0.0.11
      - KONG_TEST_LUA_PACKAGE_PATH=/custom_plugin/?.lua;;

      - LUA_PATH=/custom_plugin/?.lua;;
    volumes:
      - ./custom_plugin:/custom_plugin
      - ./kong:/kong
      - ./custom_plugin/kong/spec/04-custom-plugins:/kong/spec/04-custom-plugins
    entrypoint: ["sh", "-c", "make install && tail -f /dev/null"]
    depends_on:
      - kong-postgres

  kong-postgres-migration:
    build: .
    restart: on-failure
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-postgres
      - KONG_PG_USER=kong
      - KONG_PG_DATABASE=kong
#      - KONG_PG_DATABASE=kong_tests
    volumes:
      - ./kong:/kong
    entrypoint: ["sh", "-c", "make dev && kong migrations bootstrap && kong migrations up"]
    depends_on:
      - kong-postgres

  kong-postgres:
    container_name: kong-postgres
    image: postgres:11.2
    restart: always
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - "./postgres/:/var/lib/postgresql/data"